---
ID: "9912b4b5-7b52-4e8c-9b28-e8b3b3fc0d51"
Parent: "c49d922d-69c3-4027-8298-c0b07e43dfe7"
Template: "c49d922d-69c3-4027-8298-c0b07e43dfe7"
Path: /sitecore/templates/Foundation/Sublayouts/Css Class/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180117T202320Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "f4f3cf95-ee5a-49d4-9c05-e4e49bd33b68"
      Hint: Css Class
      Value: $name
